# units of density are: kilograms per meter cubed
AIR_DENSITY = 1.027
SEAWATER_DENSITY = 1025
ICEBERG_DENSITY = 917

# units of drag form coefficients are: unit-less
#ICEBERG_FORM_DRAG_COEFFICIENT_IN_AIR = 1.5
#ICEBERG_FORM_DRAG_COEFFICIENT_IN_WATER = 1.5
#ICEBERG_SKIN_DRAG_COEFFICIENT_IN_AIR = 2.5e-4
#ICEBERG_SKIN_DRAG_COEFFICIENT_IN_WATER = 5e-4

EARTH_ROTATION_RATE = 7.2921e-5  # radians per second
EARTH_RADIUS = 6378e3  # meters
